Update update-readme.yml

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -25,12 +25,27 @@ jobs:
     - name: Fetch GitHub Stats
       id: github_stats
       run: |
-        total_contributions=$(curl -s https://api.github.com/users/himasnhu-at | jq .public_repos)
-        public_repos=$(curl -s https://api.github.com/users/himasnhu-at | jq .public_repos)
+        # Fetch public repositories and handle response
+        public_repos=$(curl -s https://api.github.com/users/himasnhu-at | jq '.public_repos')
+        if [ $? -ne 0 ]; then
+          echo "Error fetching public repositories"
+          exit 1
+        fi
+        
+        # Fetch private repositories
         private_repos=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/repos?per_page=1 | jq '. | length')
-        lifetime_contributions=$(curl -s https://github-contributions-api.now.sh/v1/himasnhu-at | jq '.years[0].total')
+        if [ $? -ne 0 ]; then
+          echo "Error fetching private repositories"
+          exit 1
+        fi
 
-        echo "TOTAL_CONTRIBUTIONS=$total_contributions" >> $GITHUB_ENV
+        # Fetch lifetime contributions
+        lifetime_contributions=$(curl -s https://github-contributions-api.now.sh/v1/himasnhu-at | jq '.years[0].total')
+        if [ $? -ne 0 ]; then
+          echo "Error fetching lifetime contributions"
+          exit 1
+        fi
+
         echo "PUBLIC_REPOS=$public_repos" >> $GITHUB_ENV
         echo "PRIVATE_REPOS=$private_repos" >> $GITHUB_ENV
         echo "LIFETIME_CONTRIBUTIONS=$lifetime_contributions" >> $GITHUB_ENV
@@ -38,14 +53,14 @@ jobs:
     - name: Update README.md
       run: |
         LOC=$(echo ${{ env.LOC }})
-        TOTAL_CONTRIBUTIONS=$(echo ${{ env.TOTAL_CONTRIBUTIONS }})
         PUBLIC_REPOS=$(echo ${{ env.PUBLIC_REPOS }})
         PRIVATE_REPOS=$(echo ${{ env.PRIVATE_REPOS }})
         LIFETIME_CONTRIBUTIONS=$(echo ${{ env.LIFETIME_CONTRIBUTIONS }})
 
+        # Replace the lines in README.md
         sed -i "s|![Lines of Code](.*)|![Lines of Code](https://img.shields.io/badge/LOC-${LOC}%20Lines-blue)|" README.md
         sed -i "/---/,+5d" README.md
-        echo -e "---\n** My Github Stats **\n\n> $TOTAL_CONTRIBUTIONS contributions in 2024\n  >\n> $LIFETIME_CONTRIBUTIONS lifetime contributions\n  >\n> $PRIVATE_REPOS private repositories\n  >\n> $PUBLIC_REPOS public repositories\n---" >> README.md
+        echo -e "---\n** My Github Stats **\n\n> Contributions in 2024: $TOTAL_CONTRIBUTIONS\n  >\n> Lifetime Contributions: $LIFETIME_CONTRIBUTIONS\n  >\n> Private Repositories: $PRIVATE_REPOS\n  >\n> Public Repositories: $PUBLIC_REPOS\n---" >> README.md
 
     - name: Commit and Push Changes
       run: |
